### ISSUE TITLE
Signing in to Portal Generates a Bad Request (400)

### ISSUE THREAD

**Issue by zinfin** [Esri/maps-app-android#121]
Running a Nexus 7 on version 5.1.1  (API 22).  To reproduce:
1) Go to developers.arcgs.com 
2) Navigate to https://developers.arcgis.com/applications/#/ 
3) Press “Register New Application” 
4) Enter a title (“map-app2”), tags(“example”) and click “Register New Application” 
5) Copy the client id to the app_settings.xml in the map-app
6) Run the map-app on your device, Sign In in the menu drawer and enter "www.arcgis.com", click "Continue"
6) Note the resulting web page with the 400 error.

**Comment by doneill** [comment]
This is due to an invalid site redirect URI.  To configure a redirect URI

1. Sign into ArcGIS for developers
2. Go to the **Authentication** tab for your maps-app application on ArcGIS for Developers
3. Add a new redirect URI to the list at the bottom of the page.  These redirect URI's represent a valid place that a user can be redirected to after a successful sign on.

You can also configure a [redirect URI on ArcGIS Online](http://doc.arcgis.com/en/arcgis-online/share-maps/add-items.htm#REG_APP) or your own on-premise portal.  You cannot use a redirect URI that begins with `file://`.

**Comment by doneill** [comment]
@zinfin We should better handle the exception when attempting to log in w/o a redirect URI in place.

**Comment by doneill** [comment]
Verified in #133
