### ISSUE TITLE
Base maps not showing up

### ISSUE THREAD

**Issue by marastoica** [Esri/maps-app-android#137]
@zinfin when loading the app on the tablet, and trying to change base maps (not signed in), only one base map shows up. When clicked, it doesn't load, screen turns black.

**Comment by doneill** [comment]
@marastoica What size tablet and which branch are you using?

**Comment by zinfin** [comment]
@doneill @marastoica Turns out I loaded Mara's nexus 7 tablet with the wrong branch.  Have re-deployed on the nexus 7 with the quart-dev branch and am seeing the same behavior.  Also seeing this behavior on the nexus 5 with the same branch. Fetching basemaps seems to be one of the problems.  While the basemaps are retrieved, fetching thumbnails isn't always successful (BasemapsDialogFragment.getBasemapThumbnails().  @doneill can you replicate this behavior on any of your devices?

**Comment by doneill** [comment]
@zinfin @marastoica Does this still happen?  I am unable to reproduce.

**Comment by zinfin** [comment]
@marastoica @doneill I don't think this is happening anymore.  I'm also unable to repro.
