### ISSUE TITLE
Application stops responding when the search button in action bar is tapped

### ISSUE THREAD

**Issue by doneill** [Esri/maps-app-android#60]
Tapping the search button in the `ActionBar` causes the app to crash with the following fatal exception logged:  

```
FATAL EXCEPTION: main
    Process: com.esri.android.mapsapp, PID: 7283
    java.lang.IllegalStateException: Could not find a method onSearchButtonClicked(View) in the activity class android.view.ContextThemeWrapper for onClick handler on view class android.widget.ImageButton with id 'searchButton'
```

Steps to reproduce:  
1. Tap the Search button in the `ActionBar` to initiate the Search Contextual Action Bar.  
2. Tap the Search button next to the Search Text.

**Comment by umartatweer** [comment]
how to fix this issue 

 java.lang.IllegalStateException: Could not find a method onSearchButtonClicked(View) in the activity class android.view.ContextThemeWrapper for onClick handler on view class android.widget.ImageButton with id 'searchButton'

I am following the tutorial on https://developers.arcgis.com/android/guide/add-geocoding-to-your-app.htm
and I am stuck on this issue since yesterday. 
please tell me what am i missing here...

**Comment by doneill** [comment]
@umartatweer We are working on updating the **Add geocoding to your app** tutorial you referenced and I will update this thread when we are ready to publish.
